# Use the Jupyter Spark Notebook base image
FROM bitnami/jupyter-base-notebook:4.1.6

# Set the working directory inside the image
WORKDIR /app

# Copy the notebook and datasets from your specific location into the image
COPY notebooks/medallion_architecture_airbnb.ipynb /app/
COPY datasets/ /app/datasets/

# No need to install Jupyter as it is already installed in this image
# Install additional Python dependencies if needed
RUN pip install --no-cache-dir pyspark pandas matplotlib

# Default command to run Jupyter Notebook
CMD ["start-notebook.sh", "--NotebookApp.ip='*'", "--NotebookApp.port=8888", "--NotebookApp.allow_origin='*'", "--NotebookApp.token=''"]