# Use an official Spark base image
FROM bitnami/spark:latest

# Set the working directory inside the image
WORKDIR /app

# Copy the notebook and datasets from your specific location into the image
COPY notebooks/medallion_architecture_airbnb.ipynb /app/
COPY datasets/ /app/datasets/

# Verificar que los archivos se copiaron correctamente
RUN ls -alh /app
RUN ls -alh /app/datasets

# Install additional Python dependencies (including Jupyter)
RUN pip install --no-cache-dir pyspark pandas matplotlib jupyter

# Default command to run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
