name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
    - name: Run Pytest Transformations
      run: pytest tests/test_transformations.py
    - name: Run Pytest ETL Pipeline
      run: pytest tests/test_etl_pipeline.py
